#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jersey
Version  : 2.22.2
Release  : 22
URL      : https://github.com/jersey/jersey/archive/2.22.2.tar.gz
Source0  : https://github.com/jersey/jersey/archive/2.22.2.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/sun/jersey/contribs/jersey-contribs/1.19/jersey-contribs-1.19.pom
Source2  : https://repo.maven.apache.org/maven2/com/sun/jersey/contribs/jersey-contribs/1.9/jersey-contribs-1.9.pom
Source3  : https://repo.maven.apache.org/maven2/com/sun/jersey/contribs/jersey-guice/1.19/jersey-guice-1.19.jar
Source4  : https://repo.maven.apache.org/maven2/com/sun/jersey/contribs/jersey-guice/1.19/jersey-guice-1.19.pom
Source5  : https://repo.maven.apache.org/maven2/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar
Source6  : https://repo.maven.apache.org/maven2/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.pom
Source7  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-core/1.0/jersey-core-1.0.jar
Source8  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-core/1.0/jersey-core-1.0.pom
Source9  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar
Source10  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.pom
Source11  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar
Source12  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.pom
Source13  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-project/1.0/jersey-project-1.0.pom
Source14  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-project/1.19/jersey-project-1.19.pom
Source15  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-project/1.9/jersey-project-1.9.pom
Source16  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-server/1.0/jersey-server-1.0.jar
Source17  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-server/1.0/jersey-server-1.0.pom
Source18  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-server/1.19/jersey-server-1.19.jar
Source19  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-server/1.19/jersey-server-1.19.pom
Source20  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar
Source21  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.pom
Source22  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-servlet/1.19/jersey-servlet-1.19.jar
Source23  : https://repo.maven.apache.org/maven2/com/sun/jersey/jersey-servlet/1.19/jersey-servlet-1.19.pom
Source24  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.jar
Source25  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.pom
Source26  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.jar
Source27  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.pom
Source28  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet/2.28/jersey-container-servlet-2.28.jar
Source29  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet/2.28/jersey-container-servlet-2.28.pom
Source30  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.jar
Source31  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.pom
Source32  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.jar
Source33  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.pom
Source34  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/inject/jersey-hk2/2.28/jersey-hk2-2.28.jar
Source35  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/inject/jersey-hk2/2.28/jersey-hk2-2.28.pom
Source36  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/inject/project/2.28/project-2.28.pom
Source37  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.jar
Source38  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.pom
Source39  : https://repo.maven.apache.org/maven2/org/glassfish/jersey/media/project/2.22.2/project-2.22.2.pom
Source40  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.13/jersey-client-1.13.jar
Source41  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.13/jersey-client-1.13.pom
Source42  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar
Source43  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.pom
Source44  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar
Source45  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.pom
Source46  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.1.5.1/jersey-core-1.1.5.1.jar
Source47  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.1.5.1/jersey-core-1.1.5.1.pom
Source48  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.13/jersey-core-1.13.jar
Source49  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.13/jersey-core-1.13.pom
Source50  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.17.1/jersey-core-1.17.1.jar
Source51  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.17.1/jersey-core-1.17.1.pom
Source52  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar
Source53  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.pom
Source54  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar
Source55  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.pom
Source56  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-grizzly2-servlet/1.19/jersey-grizzly2-servlet-1.19.jar
Source57  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-grizzly2-servlet/1.19/jersey-grizzly2-servlet-1.19.pom
Source58  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-grizzly2/1.19/jersey-grizzly2-1.19.jar
Source59  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-grizzly2/1.19/jersey-grizzly2-1.19.pom
Source60  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-json/1.1.5.1/jersey-json-1.1.5.1.jar
Source61  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-json/1.1.5.1/jersey-json-1.1.5.1.pom
Source62  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-project/1.1.5.1/jersey-project-1.1.5.1.pom
Source63  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-project/1.13/jersey-project-1.13.pom
Source64  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-project/1.19/jersey-project-1.19.pom
Source65  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-project/1.9/jersey-project-1.9.pom
Source66  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-server/1.1.5.1/jersey-server-1.1.5.1.jar
Source67  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-server/1.1.5.1/jersey-server-1.1.5.1.pom
Source68  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-test-framework/1.19/jersey-test-framework-1.19.pom
Source69  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19/jersey-test-framework-core-1.19.jar
Source70  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19/jersey-test-framework-core-1.19.pom
Source71  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19/jersey-test-framework-grizzly2-1.19.jar
Source72  : https://repo1.maven.org/maven2/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19/jersey-test-framework-grizzly2-1.19.pom
Source73  : https://repo1.maven.org/maven2/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar
Source74  : https://repo1.maven.org/maven2/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.pom
Source75  : https://repo1.maven.org/maven2/org/glassfish/jersey/bundles/repackaged/project/2.22.2/project-2.22.2.pom
Source76  : https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.jar
Source77  : https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.pom
Source78  : https://repo1.maven.org/maven2/org/glassfish/jersey/jersey-bom/2.25/jersey-bom-2.25.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0 CDDL-1.1 GPL-2.0
Requires: mvn-jersey-data = %{version}-%{release}
Requires: mvn-jersey-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn
BuildRequires : gradle
Patch1: jersey-project.patch
Patch2: jersey-project-2.28.patch

%description
This directory contains Jersey & JAX-RS tools - ant tasks, maven plugins, shell scripts etc.

%package data
Summary: data components for the mvn-jersey package.
Group: Data

%description data
data components for the mvn-jersey package.


%package license
Summary: license components for the mvn-jersey package.
Group: Default

%description license
license components for the mvn-jersey package.


%prep
## prep_prepend content
mkdir -p project
cd project
%patch1 -p1
%patch2 -p1
cd ../
## prep_prepend end
%setup -q -n jersey-2.22.2
%patch1 -p1
%patch2 -p1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jersey
cp LICENSE.html %{buildroot}/usr/share/package-licenses/mvn-jersey/LICENSE.html
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-jersey/LICENSE.txt
cp etc/config/copyright.txt %{buildroot}/usr/share/package-licenses/mvn-jersey/etc_config_copyright.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-contribs/1.19
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-contribs/1.19/jersey-contribs-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-contribs/1.9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-contribs/1.9/jersey-contribs-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.19
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.19/jersey-guice-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.19
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.19/jersey-guice-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.0/jersey-core-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.0/jersey-core-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.19
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.19
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.9
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.9
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.0/jersey-project-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.19
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.19/jersey-project-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.9
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.9/jersey-project-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.0
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.0/jersey-server-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.0/jersey-server-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.19
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.19/jersey-server-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.19
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.19/jersey-server-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.9
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.9
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-servlet/1.19
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-servlet/1.19/jersey-servlet-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-servlet/1.19
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-servlet/1.19/jersey-servlet-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.28
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.28/jersey-container-servlet-2.28.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.28
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.28/jersey-container-servlet-2.28.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.28
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.28/jersey-hk2-2.28.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.28
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.28/jersey-hk2-2.28.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/inject/project/2.28
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/inject/project/2.28/project-2.28.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/media/project/2.22.2
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/media/project/2.22.2/project-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.13
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.13/jersey-client-1.13.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.13
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.13/jersey-client-1.13.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.19
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.19
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.9
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.9
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.1.5.1
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.1.5.1/jersey-core-1.1.5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.1.5.1
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.1.5.1/jersey-core-1.1.5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.13
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.13/jersey-core-1.13.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.13
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.13/jersey-core-1.13.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.17.1
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.17.1/jersey-core-1.17.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.17.1
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.17.1/jersey-core-1.17.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.19
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.19
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.9
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.9
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2-servlet/1.19
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2-servlet/1.19/jersey-grizzly2-servlet-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2-servlet/1.19
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2-servlet/1.19/jersey-grizzly2-servlet-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2/1.19
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2/1.19/jersey-grizzly2-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2/1.19
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2/1.19/jersey-grizzly2-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.1.5.1
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.1.5.1/jersey-json-1.1.5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.1.5.1
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.1.5.1/jersey-json-1.1.5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.1.5.1
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.1.5.1/jersey-project-1.1.5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.13
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.13/jersey-project-1.13.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.19
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.19/jersey-project-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.9
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.9/jersey-project-1.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.1.5.1
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.1.5.1/jersey-server-1.1.5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.1.5.1
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.1.5.1/jersey-server-1.1.5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/1.19
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/1.19/jersey-test-framework-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19/jersey-test-framework-core-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19/jersey-test-framework-core-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19/jersey-test-framework-grizzly2-1.19.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19/jersey-test-framework-grizzly2-1.19.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2
cp %{SOURCE74} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/project/2.22.2
cp %{SOURCE75} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/project/2.22.2/project-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2
cp %{SOURCE76} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2
cp %{SOURCE77} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/jersey-bom/2.25
cp %{SOURCE78} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/jersey-bom/2.25/jersey-bom-2.25.pom

## install_append content
cp -r ../project/* %{buildroot}/usr/share/java/.m2/repository
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-contribs/1.19/jersey-contribs-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-contribs/1.9/jersey-contribs-1.9.pom
/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.19/jersey-guice-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.19/jersey-guice-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar
/usr/share/java/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.13/jersey-client-1.13.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.13/jersey-client-1.13.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.0/jersey-core-1.0.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.0/jersey-core-1.0.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.1.5.1/jersey-core-1.1.5.1.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.1.5.1/jersey-core-1.1.5.1.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.13/jersey-core-1.13.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.13/jersey-core-1.13.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.17.1/jersey-core-1.17.1.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.17.1/jersey-core-1.17.1.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2-servlet/1.19/jersey-grizzly2-servlet-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2-servlet/1.19/jersey-grizzly2-servlet-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2/1.19/jersey-grizzly2-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-grizzly2/1.19/jersey-grizzly2-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.1.5.1/jersey-json-1.1.5.1.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.1.5.1/jersey-json-1.1.5.1.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.0/jersey-project-1.0.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.1.5.1/jersey-project-1.1.5.1.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.13/jersey-project-1.13.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.19/jersey-project-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-project/1.9/jersey-project-1.9.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.0/jersey-server-1.0.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.0/jersey-server-1.0.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.1.5.1/jersey-server-1.1.5.1.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.1.5.1/jersey-server-1.1.5.1.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.19/jersey-server-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.19/jersey-server-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-servlet/1.19/jersey-servlet-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-servlet/1.19/jersey-servlet-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/1.19/jersey-test-framework-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19/jersey-test-framework-core-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-core/1.19/jersey-test-framework-core-1.19.pom
/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19/jersey-test-framework-grizzly2-1.19.jar
/usr/share/java/.m2/repository/com/sun/jersey/jersey-test-framework/jersey-test-framework-grizzly2/1.19/jersey-test-framework-grizzly2-1.19.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/project/2.22.2/project-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/project/2.22.2/project-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.28/jersey-container-servlet-2.28.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.28/jersey-container-servlet-2.28.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/project/2.22.2/project-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/containers/project/2.28/project-2.28.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.28/jersey-hk2-2.28.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.28/jersey-hk2-2.28.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/inject/project/2.28/project-2.28.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/jersey-bom/2.25/jersey-bom-2.25.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/media/project/2.22.2/project-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/project/2.22.2/project-2.22.2.pom
/usr/share/java/.m2/repository/org/glassfish/jersey/project/2.28/project-2.28.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jersey/LICENSE.html
/usr/share/package-licenses/mvn-jersey/LICENSE.txt
/usr/share/package-licenses/mvn-jersey/etc_config_copyright.txt
