#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jersey
Version  : 2.22.2
Release  : 1
URL      : https://github.com/jersey/jersey/archive/2.22.2.tar.gz
Source0  : https://github.com/jersey/jersey/archive/2.22.2.tar.gz
Source1  : https://repo1.maven.org/maven2/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar
Source2  : https://repo1.maven.org/maven2/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0 CDDL-1.1 GPL-2.0
Requires: mvn-jersey-data = %{version}-%{release}

%description
This directory contains Jersey & JAX-RS tools - ant tasks, maven plugins, shell scripts etc.

%package data
Summary: data components for the mvn-jersey package.
Group: Data

%description data
data components for the mvn-jersey package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar
/usr/share/java/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.pom
